### ISSUE TITLE
init_gplay - Incorrect credentials, login failed

### ISSUE THREAD

**Issue by Dapipminmonkey** [fredley/play-pi#20]
I attempted to follow the instructions given, but whenever I run ./manage.py init_gplay I receive "Incorrect credentials, login failed".  I have a Googel Apps account (but have also tried my gmail account), and I am not using 2 Factor Auth.

**Comment by markjewiss** [comment]
Am seeing the same issue here. Were you able to get past this?

**Comment by buzzbo** [comment]
I have this problem too and I'm certain my Google credentials are correct.

**Comment by fredley** [comment]
This is probably due to gmusicapi - Google seems to change the authentication method reasonably often. I don't have time, but if someone wants to investigate, the docs are here: https://unofficial-google-music-api.readthedocs.org/en/latest/

**Comment by shtemberko** [comment]
Sup, guys.

I was able to get this fixed. [Here](https://github.com/fredley/play-pi/pull/23) is my pull request.
Simply get this change and run `sudo pip install -r requirements.txt` (will update your gmusicapi version) again. 

PS: if you will run into some errors on updating gmusicapi, try to:
1. upgrade you pip ( `sudo pip install --upgrade pip`)
2. try installing following: `sudo apt-get install python-dev libffi-dev libssl-dev`

Cheers!

**Comment by fredley** [comment]
Fixed in https://github.com/fredley/play-pi/commit/8e6c0cdb3a0b62d810019bb6b1aac5e97bd78155 by @shtemberko!
