### ISSUE TITLE
Error on sudo pip install -r requirements.txt

### ISSUE THREAD

**Issue by ebeyer** [fredley/play-pi#29]
I'm far from any kind of expert, but I appear to be having an error on building (something).  My error log is in this pastebin: http://pastebin.com/qJqGBHfZ

**Comment by fredley** [comment]
Not sure why this is happening, try running `sudo apt-get install libffi` then rerunning the command.

**Comment by ebeyer** [comment]
sudo apt-get update && sudo apt-get install libffi --> E: Unable to locate package libffi

**Comment by fredley** [comment]
According to http://raspberrypi.stackexchange.com/questions/37281/cant-install-flask-bcrypt-libffi-is-missing, the command is actually `sudo apt-get install libffi-dev`, sorry.

**Comment by ebeyer** [comment]
I apologize, too, as my error is actually with the previous step, 'sudo pip install -U setuptools': http://pastebin.com/MfTtSnzC

**Comment by fredley** [comment]
Haha, no problem, glad you sorted it out.

**Comment by ebeyer** [comment]
NOOO... wait... it still doesn't build.  Am I looking at this wrong?
