### ISSUE TITLE
ImportError: No module named gmusicapi

### ISSUE THREAD

**Issue by CalebVred** [fredley/play-pi#34]
When I try to set up Django, it says "ImportError: No module named gmusicapi"

Any idea how I can fix this?

**Comment by mick88** [comment]
Did you run the pip install command? Did it complete successfully?

**Comment by CalebVred** [comment]
I tried again, and it seems to have worked!

I do have one question: where is 'settings.py' located? I can't seem to find it in any directories.

**Comment by fredley** [comment]
https://github.com/fredley/play-pi/blob/master/play_pi/settings.py

**Comment by CalebVred** [comment]
I ran the command './manage.py migrate' and it gave me the error: 
"django.db.utils.OperationalError: unable to open database file".

 Would this be because of incorrect credentials in local_settings.py, or do I need to add some extra info to settings.py?
